services:
    lesson-service:
        container_name: education-content-service
        build:
            context: ./backend/EducationContentService
            dockerfile: Dockerfile
        ports:
            - "9001:9001" 
        restart: always

    seq:
        container_name: seq
        image: datalust/seq:latest
        environment:
            ACCEPT_EULA: "Y"
            SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
        ports:
            - "8081:80"
            - "5341:5341"
        restart: always